
@domain=http://localhost:3001
# @domain=https://s-api.wu67.win
### http test
GET  {{domain}}/hello


####
GET {{domain}}/sms/list?limit=10


####
POST {{domain}}/sms/receive

{
  "pwd": "you pwd here",
  "fromPhone": "17612341234",
  "phone": "17612341235",
  "content": "sms test content here"
}
